### ISSUE TITLE
Error accessing public internet when saving credential

### ISSUE THREAD

**Issue by jgallucci32** [joval/jOVAL#11]
This one has me spooked a bit. When attempting to save a credential (username/password) in the Joval application, the following error message is displayed indicating the application failed to connect to the public internet. Using wireshark, the Joval application is making an oubound TCP/443 connection to 13.89.220.65 when saving the credential.

Here is the error message
```
Credential Storage Error:

There was a problem saving the credential: jkeyring.KeyringException: java.lang.Exception: CryptProtectData failed: -2146892987 
at jkeyring.impl.crypto.CryptoProvider.save(CryptoProvider.java:103) 
at org.joval.professional.webapp.CredentialManager.insertUpdate(CredentialManager.java:495) 
at org.joval.professional.webapp.CredentialManager.access$100(CredentialManager.java:49) 
at org.joval.professional.webapp.CredentialManager$ApiExports.add(CredentialManager.java:310) 
at org.joval.professional.webapp.Servlet.doPost(Servlet.java:358) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) 
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686) 
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) 
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) 
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428) 
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) 
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) 
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) 
at org.eclipse.jetty.server.Server.handle(Server.java:370) 
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) 
at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) 
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) 
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) 
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) 
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) 
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) 
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) 
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) 
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) 
at java.lang.Thread.run(Unknown Source) Caused by: java.lang.Exception: CryptProtectData failed: -2146892987 
at jkeyring.impl.win32.DPAPIEncryption.encrypt(DPAPIEncryption.java:90) 
at jkeyring.impl.crypto.CryptoProvider._save(CryptoProvider.java:172) 
at jkeyring.impl.crypto.CryptoProvider.save(CryptoProvider.java:101) 
at org.joval.professional.webapp.CredentialManager.insertUpdate(CredentialManager.java:495) 
at org.joval.professional.webapp.CredentialManager.access$100(CredentialManager.java:49) 
at org.joval.professional.webapp.CredentialManager$ApiExports.add(CredentialManager.java:310) 
at org.joval.professional.webapp.Servlet.doPost(Servlet.java:358) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) 
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686) 
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) 
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) 
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428) 
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) 
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) 
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) 
at org.eclipse.jetty.server.Server.handle(Server.java:370) 
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) 
at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) 
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) 
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) 
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) 
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) 
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) 
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) 
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) 
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) 
at java.lang.Thread.run(Unknown Source)
```

**Comment by jgallucci32** [comment]
Ok not as scary as I originally thought. That IP address ties back to Microsoft so I'm thinking there may be some tie-in to the credential manager / encryption module. Still, what does  MS want with my password?!

![image](https://user-images.githubusercontent.com/9018897/53919403-c502c380-401e-11e9-9c9e-c22c4a191daf.png)

**Comment by solind** [comment]
Hi, yes, I reverse looked up the IP when you first posted and noticed it was in a block reserved by Microsoft.  This certainly isn't our product doing this, and I have no idea why Windows would need to reach out to Microsoft for the Data Protection API to work.

If you're curious about jKeyring, check out the jKeyring project:
https://github.com/joval/jKeyring

It's essentially just the native Keyring code lifted from the Netbeans IDE.

**Comment by jgallucci32** [comment]
After further investigation it was an issue related to the Web Credential Manager in Windows 10. Opening the credential manager caused an error regarding lack of trust to domain. I tried it on a different Win10 box which did not have that issue and jOVAL worked as expected.                                                                                                                                                                                                                From: David SolinSent: Thursday, March 7, 2019 6:55 AMTo: joval/jOVALReply To: joval/jOVALCc: jgallucci32; AuthorSubject: Re: [joval/jOVAL] Error accessing public internet when saving credential (#11)Hi, yes, I reverse looked up the IP when you first posted and noticed it was in a block reserved by Microsoft.  This certainly isn't our product doing this, and I have no idea why Windows would need to reach out to Microsoft for the Data Protection API to work.
If you're curious about jKeyring, check out the jKeyring project:
https://github.com/joval/jKeyring
It's essentially just the native Keyring code lifted from the Netbeans IDE.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joval/jOVAL","title":"joval/jOVAL","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/joval/jOVAL"}},"updates":{"snippets":[{"icon":"PERSON","message":"@solind in #11: Hi, yes, I reverse looked up the IP when you first posted and noticed it was in a block reserved by Microsoft.  This certainly isn't our product doing this, and I have no idea why Windows would need to reach out to Microsoft for the Data Protection API to work.\r\n\r\nIf you're curious about jKeyring, check out the jKeyring project:\r\nhttps://github.com/joval/jKeyring\r\n\r\nIt's essentially just the native Keyring code lifted from the Netbeans IDE."}],"action":{"name":"View Issue","url":"https://github.com/joval/jOVAL/issues/11#issuecomment-470557120"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/joval/jOVAL/issues/11#issuecomment-470557120",
"url": "https://github.com/joval/jOVAL/issues/11#issuecomment-470557120",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
